
GET http://localhost:3000/todos

###

POST http://localhost:3000/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

###

DELETE http://localhost:3000/todo/delete/65aa22caf6a7db7a361c154e


###
PUT http://localhost:3000/todo/complete/65a9a7d082e4f22ae6a0f2f3
